name: Update App

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies     
      run : yarn install
    - name: Build Web site
      run : yarn run build 
    - name: Restrt Websit    
      run : pm2 restart fb
    
